apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  type: {{ .Values.service.type }}
  selector:
    purpose: helm-dp-service
    project: roboshop 
  ports:
    - protocol: TCP
      port: {{ .Values.service.servicePort }}  # service port number
      targetPort: 80  #container port number
      nodePort: 30007